name: "Primer Action"

#Trigger
on:
  push:
    branches: ["feature/clase-1"]

jobs:
  deploy-primer-action:
    runs-on: ubuntu-latest #Runners
    steps:
      - run: echo "Hacemos pull del código"
      - run: echo "Correar migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
